let STATE=null, PARAMS=null; const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
async function api(p,o={}){let r=await fetch(p,{headers:{'Content-Type':'application/json'},...o});return await r.json();}
function esc(s){return String(s??"").replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]));}
function modal(t,b){$("#modalTitle").textContent=t;$("#modalBody").innerHTML=b;$("#modal").classList.remove("hidden");}
$("#modalClose").onclick=()=>$("#modal").classList.add("hidden");
$$(".nav").forEach(b=>b.onclick=()=>{ $$(".nav").forEach(x=>x.classList.remove("active")); b.classList.add("active"); $$(".tab").forEach(t=>t.classList.remove("active")); $("#tab-"+b.dataset.tab).classList.add("active"); });
async function load(){STATE=await api('/api/state'); PARAMS=STATE.params||{}; render();}
function render(){let a=STATE.audit||{},ch=STATE.champion||{},tr=STATE.training||{}; $("#topSize").textContent=(a.size_kb||"--")+"KB";$("#topChampion").textContent=ch.score||"--";$("#championScore").textContent=ch.score||"--";$("#candidateScore").textContent=(STATE.candidate||{}).score??"idle";$("#solverCardSize").textContent=(a.size_kb||"--")+"KB";$("#heroState").textContent=tr.running?"TRAINING":"READY";renderEvents();renderMini();renderCharts();renderOffice();renderFlow();renderTimeline();renderRSI();renderScores();renderForensics();renderAudit(a);renderData();renderParams();renderBackups();}
function renderRSI(){let r=STATE.rsi||{},ops=r.operators||{},sum=r.summary||{},learned=r.learned_ops||[];let rows=Object.entries(ops).sort((x,y)=>y[1].ucb-x[1].ucb).map(([name,s])=>`<tr class="${learned.includes(name)?"learned":""}"><td>${esc(name)}${learned.includes(name)?' <span class="tag promoted">L3</span>':""}</td><td>${s.kind}</td><td>${s.uses}</td><td>${s.wins}</td><td>${(s.win_rate*100).toFixed(0)}%</td><td>${s.avg_gain_pct}</td><td><b>${s.ucb}</b></td></tr>`).join("")||'<tr><td colspan="7">尚无算子数据，启动一次训练。</td></tr>';$("#rsiPanel").innerHTML=`<div class="rsi-cards"><div class="card"><small>L1 晋升次数</small><b>${sum.promoted??0}</b><p>solver CONFIG 写回成功数</p></div><div class="card"><small>L2 累计试验</small><b>${sum.trials??0}</b><p>经验库 trials 总数</p></div><div class="card"><small>L3 自写算子</small><b>${learned.length}</b><p>${esc(learned.join(", ")||"等待元步合成（需 LLM key）")}</p></div><div class="card"><small>最佳筛选</small><b>${sum.best_screen?sum.best_screen.gain_pct+"%":"--"}</b><p>${sum.best_screen?esc(sum.best_screen.scene+" · "+sum.best_screen.op):"暂无"}</p></div></div><table class="score-row head rsi-table"><tr class="score-row head"><td>算子</td><td>类型</td><td>使用</td><td>胜出</td><td>胜率</td><td>平均增益%</td><td>UCB</td></tr>${rows}</table>`;}
function renderMini(){$("#miniLog").innerHTML=(STATE.events||[]).slice(-6).map(e=>`<div>${e.time} ${e.agent}: ${esc(e.message).slice(0,42)}</div>`).join("");}
function renderEvents(){let box=$("#events");box.innerHTML="";(STATE.events||[]).slice().reverse().slice(0,80).forEach(e=>{box.innerHTML+=`<div class="event"><span>${e.time}</span><b>${esc(e.agent)}</b> · ${esc(e.message)}</div>`});}
function renderCharts(){let bars=STATE.case_results||[],max=Math.max(...bars.map(x=>x.champion),1);$("#barChart").innerHTML=bars.map(b=>`<div class="bar-row"><div class="bar-label">${b.case.replace("_seed","")}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(3,b.champion/max*100)}%"></div></div><div class="bar-val">${b.champion}</div></div>`).join("");drawLine();drawRadar();drawHeat();drawMap();}
function drawLine(){let svg=$("#lineChart"),d=STATE.charts?.trend||[];let w=420,h=280,p=34,min=Math.min(...d.map(x=>x.avg)),max=Math.max(...d.map(x=>x.avg));let pts=d.map((x,i)=>[p+i*(w-2*p)/Math.max(1,d.length-1),h-p-(x.avg-min)/Math.max(.001,max-min)*(h-2*p),x]);svg.setAttribute("viewBox",`0 0 ${w} ${h}`);svg.innerHTML=`<polyline fill="none" stroke="#45a3ff" stroke-width="3" points="${pts.map(p=>p[0]+','+p[1]).join(' ')}"/>`+pts.map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="5" fill="#2be88a"></circle><text x="${p[0]-12}" y="${h-8}" fill="#8f98ad" font-size="12">${p[2].round}</text>`).join("");}
function drawRadar(){let svg=$("#radarChart"),items=STATE.charts?.radar||[];let w=280,h=250,cx=140,cy=125,r=88,n=items.length;let coords=items.map((it,i)=>{let a=-Math.PI/2+i*2*Math.PI/n,rr=r*it.value/100;return [cx+Math.cos(a)*rr,cy+Math.sin(a)*rr,it,a]});let outer=items.map((it,i)=>{let a=-Math.PI/2+i*2*Math.PI/n;return [cx+Math.cos(a)*r,cy+Math.sin(a)*r,it,a]});svg.setAttribute("viewBox",`0 0 ${w} ${h}`);svg.innerHTML=[20,40,60,80,100].map(v=>{let rr=r*v/100,ps=items.map((it,i)=>{let a=-Math.PI/2+i*2*Math.PI/n;return (cx+Math.cos(a)*rr)+','+(cy+Math.sin(a)*rr)}).join(' ');return `<polygon points="${ps}" fill="none" stroke="#30384b"/>`}).join("")+outer.map(p=>`<line x1="${cx}" y1="${cy}" x2="${p[0]}" y2="${p[1]}" stroke="#30384b"/><text x="${p[0]+Math.cos(p[3])*14-18}" y="${p[1]+Math.sin(p[3])*14}" fill="#b9c4d8" font-size="11">${p[2].axis}</text>`).join("")+`<polygon points="${coords.map(p=>p[0]+','+p[1]).join(' ')}" fill="#45a3ff55" stroke="#2be88a" stroke-width="3"/>`;}
function drawHeat(){let data=STATE.charts?.heatmap||[];$("#heatmap").innerHTML=data.flatMap(r=>r.map(v=>`<div class="heat-cell" style="background:rgba(${Math.round(40+120*v)},${Math.round(80+160*v)},${Math.round(130+80*v)},.75)">${Math.round(v*100)}</div>`)).join("");}
function drawMap(){let nodes=[["medium",50,50],["high_noise",18,30],["low",22,76],["large",80,30],["scarce",78,75],["protected",52,88]];$("#sceneMap").innerHTML=nodes.map(n=>`<div class="scene-node" style="left:${n[1]}%;top:${n[2]}%">${n[0]}</div>`).join("")+`<div class="scene-link" style="left:25%;top:42%;width:46%;transform:rotate(15deg)"></div>`;}
function renderOffice(){let box=$("#office");box.innerHTML="";(STATE.agents||[]).forEach(a=>{box.innerHTML+=`<div class="desk" style="left:${a.x}%;top:${a.y}%"></div><div class="agent" data-id="${a.id}" style="left:${a.x}%;top:${a.y-4}%;--c:${a.color}"></div><div class="agent-name" data-id="${a.id}" style="left:${a.x}%;top:${a.y+9}%">${a.name}<div class="agent-status">${a.role} · ${a.status} · ${a.energy}%</div></div>`});$$("[data-id]").forEach(x=>x.onclick=()=>showAgent(STATE.agents.find(a=>a.id===x.dataset.id)));}
function showAgent(a){$("#agentDetailTitle").textContent=a.name;$("#agentDetail").innerHTML=`<p><b>职责：</b>${esc(a.role)}</p><p><b>状态：</b>${esc(a.status)} · ${a.energy}%</p><h3>关键操作</h3><ul>${(a.ops||[]).map(o=>`<li>${esc(o)}</li>`).join("")}</ul><h3>数据</h3><pre class="code">${esc(JSON.stringify(a.data||{},null,2))}</pre>`;}
function renderFlow(){let box=$("#flowNodes");box.innerHTML="";(STATE.flow_nodes||[]).forEach(n=>{let b=document.createElement("button");b.className="node "+(n.status==="armed"?"guard":"");b.textContent=n.id;b.onclick=()=>{$("#flowDetailTitle").textContent=n.id;$("#flowDetail").textContent=`status: ${n.status}\n\n${n.detail}\n\ncode:\n${n.code}`};box.appendChild(b);});}
function renderTimeline(){let tr=STATE.training||{},pct=tr.total_rounds?Math.round((tr.round||0)/tr.total_rounds*100):0;$("#progressBar").style.width=pct+"%";$("#trainStatus").textContent=`mode=${tr.mode||"idle"} · running=${!!tr.running} · round=${tr.round||0}/${tr.total_rounds||0}`;$("#timeline").innerHTML=(tr.timeline||[]).slice().reverse().map(x=>`<div class="round"><b>Round ${x.round} · ${x.scene} · ${x.agent}</b><p>${esc(x.message)}</p><pre>${esc(JSON.stringify(x.metrics||{},null,2))}</pre></div>`).join("");}
function renderScores(){let rows=`<div class="score-row head"><div>case</div><div>champion</div><div>candidate</div><div>delta</div><div>assigned</div><div>status</div></div>`+(STATE.case_results||[]).map(r=>`<div class="score-row"><div>${r.case}</div><div>${r.champion}</div><div>${r.candidate??"--"}</div><div>${r.delta??"--"}</div><div>${r.assigned}</div><div><span class="tag ${r.status}">${r.status}</span></div></div>`).join("");$("#scoreTable").innerHTML=rows;}
function renderForensics(){$("#forensics").innerHTML=(STATE.forensics||[]).map(f=>`<div class="forensic ${f.severity}"><b>${esc(f.scene)}</b><p>${esc(f.finding)}</p><div class="diff"><pre class="code wrong">${esc(f.wrong_code)}</pre><pre class="code fixed">${esc(f.fixed_code)}</pre></div></div>`).join("");}
function renderAudit(a){$("#auditBox").innerHTML=`<div class="card"><small>size</small><b>${a.size_kb||0}KB</b><p>risk=${a.risk} · funcs=${a.functions||0} · classes=${a.classes||0} · lines=${a.lines||0}</p><p>dangerous: ${(a.dangerous||[]).join(", ")||"none"}</p><p>sha=${a.sha256||"--"}</p></div>`;}
function renderData(){let p=STATE.large_seed301_profile||{};$("#dataProfile").innerHTML=Object.entries(p).map(([k,v])=>`<div class="profile-row"><b>${k}</b><span>${v}</span></div>`).join("");}
function renderParams(){let s=PARAMS.scenes||{};$("#sceneExplain").innerHTML=Object.entries({high_noise:"高噪声：提高 regret 权重，避免纯 score 贪心陷阱。",medium:"中规模：remove2 repair 是主收益来源。",large:"大规模：默认关闭 aggressive polish。",low_willingness:"低意愿：backup utility gate。",scarce_couriers:"骑手少：节省骑手和合单优先。",small_tiny:"小规模：冻结保护。"}).map(([k,v])=>`<div><b>${k}</b><p>${v}</p></div>`).join("");$("#paramEditor").innerHTML=Object.entries(s).map(([scene,obj])=>`<div class="param-scene"><h3>${scene}</h3><div class="param-grid">${Object.entries(obj).map(([k,v])=>`<label>${k}<input data-scene="${scene}" data-key="${k}" value="${v}"/></label>`).join("")}</div></div>`).join("");}
function collectParams(){let p=JSON.parse(JSON.stringify(PARAMS));$$("#paramEditor input").forEach(i=>{let v=i.value;if(v==="true")v=true;else if(v==="false")v=false;else if(!isNaN(Number(v))&&v.trim()!=="")v=Number(v);p.scenes[i.dataset.scene][i.dataset.key]=v});return p;}
function renderBackups(){let arr=STATE.backups||[];$("#backupList").innerHTML=arr.map(b=>`<div class="backup-card" data-name="${b.name}"><b>${b.name}</b><p>${b.mtime}</p><p>${b.size_kb}KB · sha=${b.sha256}</p><p>round=${b.manifest?.round??"--"} · tag=${b.manifest?.tag??"--"}</p></div>`).join("")||"<p>暂无备份。</p>";$$(".backup-card").forEach(c=>c.onclick=()=>confirmRollback(c.dataset.name));}
function confirmRollback(name){modal("一键回滚确认",`<p>你将回滚到：<b>${name}</b></p><p>请输入 <b>ROLLBACK</b> 后确认。</p><input id="rollbackConfirm" style="width:100%;padding:12px;border-radius:12px;background:#10141d;color:#fff;border:1px solid #3a455d" placeholder="ROLLBACK"/><br/><br/><button class="danger" id="doRollback">确认回滚</button>`);$("#doRollback").onclick=async()=>{let res=await api('/api/rollback',{method:'POST',body:JSON.stringify({name,confirm:$("#rollbackConfirm").value.trim()})});alert(res.ok?"回滚完成":res.message);$("#modal").classList.add("hidden");load();};}
async function loadLogs(){let logs=await api('/api/logs');$("#notesMd").textContent=logs["Notes.md"]||"";$("#handoverMd").textContent=logs["Handover.md"]||"";$("#agentLog").textContent=logs.agent_activity||"";$("#otherLogs").textContent=["# llm_dialogue",logs.llm_dialogue||"","# code_changes",logs.code_changes||"","# data_feedback",logs.data_feedback||"","# backup_history",logs.backup_history||""].join("\n");}
async function loadSolver(){let r=await fetch('/api/solver');$("#solverPreview").textContent=(await r.text()).slice(0,16000);}
async function startTraining(){await api('/api/train/start',{method:'POST',body:JSON.stringify({rounds:Number($("#roundInput")?.value||6),mode:$("#modeInput")?.value||"safe-medium-only"})});load();}
$("#startTrain").onclick=startTraining;$("#quickTrain").onclick=()=>{document.querySelector('[data-tab="oneclick"]').click();startTraining();};$("#stopTrain").onclick=()=>api('/api/train/stop',{method:'POST',body:"{}"}).then(load);$("#topStop").onclick=$("#stopTrain").onclick;$("#seedConfig").onclick=()=>api('/api/action',{method:'POST',body:JSON.stringify({action:"seed_config"})}).then(()=>{alert("已生成种子配置");load();});$("#distillNow").onclick=()=>api('/api/action',{method:'POST',body:JSON.stringify({action:"distill"})}).then(load);$("#saveParams").onclick=()=>api('/api/params',{method:'POST',body:JSON.stringify({params:collectParams()})}).then(()=>{alert("参数已保存");load();});$("#auditBtn").onclick=()=>api('/api/action',{method:'POST',body:JSON.stringify({action:"audit"})}).then(load);$("#makeBackup").onclick=()=>api('/api/action',{method:'POST',body:JSON.stringify({action:"backup"})}).then(x=>{alert("备份完成: "+(x.backup?.name||""));load();});$("#refreshBackups").onclick=load;
$$(".control").forEach(b=>b.onclick=()=>api('/api/action',{method:'POST',body:JSON.stringify({action:b.dataset.action,scene:b.dataset.scene})}).then(x=>{if(x.backup)alert(`备份完成\n${x.backup.name}\nsha=${x.backup.sha256}`);else alert(x.ok?"操作完成":"操作失败");load();}));
$("#sendChat").onclick=async()=>{let msg=$("#chatInput").value.trim();if(!msg)return;$("#chatLog").innerHTML+=`<div class="msg user">${esc(msg)}</div>`;$("#chatInput").value="";let res=await api('/api/chat',{method:'POST',body:JSON.stringify({message:msg})});$("#chatLog").innerHTML+=`<div class="msg llm">${esc(res.message)}</div>`;load();loadLogs();};
load();loadSolver();loadLogs();setInterval(()=>{load();loadLogs();},3000);